### ISSUE TITLE
Help needed, troubleshooting the Midilin

### ISSUE THREAD

**Issue by apandypy777** [HanYangZhao/midi_ribbon_controller#1]
Hi @HanYangZhao , 

Thanks for this great GitHub, I have built my own Midilin but need some help making it work.

**My setup:**
I am using a prototyping board at the moment before making the final assembly.
Note that I am only using one ribbon at the moment (I broke the other one while soldering >.<)

![WeChat Image_20200123215616](https://user-images.githubusercontent.com/59997340/72990529-475cc780-3e2b-11ea-8f24-e4d0e5e87961.jpg)
![WeChat Image_20200123215631](https://user-images.githubusercontent.com/59997340/72990532-47f55e00-3e2b-11ea-9803-1dd4105e3be5.jpg)

**The issues:**
1. When I calibrate the SoftPot, I follow the first time calibration instructions and upload the code to the arduino (with MIDI shield switch in PROG mode). Everything seems fine, however To calibrate each fret instead of using the middle button of the MIDI shield i have to use the A0 knob instead and turn it from counter clockwise and then clockwise to write each address, i think this is a first sign that something is wrong in my setup.
I get this messages on my serial:

![CODE](https://user-images.githubusercontent.com/59997340/72990849-dc5fc080-3e2b-11ea-9784-a39ff59d155f.JPG)

![code end](https://user-images.githubusercontent.com/59997340/72990893-ed103680-3e2b-11ea-93d8-bc4a9813ecf3.JPG)

**After calibrating the 50 frets, some strange symbols appear.** 

At this point I am not sure what to do next. What I did is re-comment the Calibrate lines, re-upload the "original" code and finally switch the MIDI shield to RUN.

I tried to connect to Ableton using the Synth 1 plugin you recommended. Ableton recognizes there is a new MIDI input, however no signals are received from it and therefore no music is being played.

![ableton](https://user-images.githubusercontent.com/59997340/72991403-e8984d80-3e2c-11ea-8eec-f788e8be2049.JPG)

My USB to MIDI cable
![WeChat Image_20200123215648](https://user-images.githubusercontent.com/59997340/72990535-47f55e00-3e2b-11ea-8299-3449a2b3d9e4.jpg)

Please let me know if you notice something that could be the problem in my setup.
Thank you in advance!

Andy

**Comment by HanYangZhao** [comment]
Hm I checked the code again, it didn't seem like you need to press a button or turn a knob when you calibrate. You might need to A0 in the beginning but not everytime. Have you tried calibrating with less frets?

**Comment by apandypy777** [comment]
My friend Marek Narozniak help me to fix this issue:

Before the calibration we needed to set the A0 knob all the way down. The middle button didn't confirm the positions, its the A0 knob. During the calibration we need to confirm pressing by turning the A0 knob all the way up.

Programming the uC must be done without the MIDI shield.
